export const CATEGORIES = [
    { id: '1', name: '1. 덮밥류 (Menu Rad Khao)', icon: 'rice_bowl' },
    { id: '2', name: '2. 메인 요리 (Main Dish)', icon: 'restaurant' },
    { id: '3', name: '3. 면 요리 (Noodle)', icon: 'ramen_dining' },
    { id: '4', name: '4. 찌개/국/커리 (Tom & Kaeng)', icon: 'soup_kitchen' },
    { id: '5', name: '5. 쏨땀 (Som Tum)', icon: 'eco' },
    { id: '6', name: '6. 이싼 음식 (Isan Food)', icon: 'local_fire_department' },
    { id: '7', name: '7. 얌 (Salad)', icon: 'spa' },
    { id: '8', name: '8. 튀김/구이 (Fried/Grilled)', icon: 'set_meal' },
    { id: '12', name: '12. 음료 (Drink)', icon: 'local_bar' },
];

export const MENU_ITEMS = [
    // --- Category 1: 덮밥류 (Menu Rad Khao) ---
    {
        id: '1-1',
        categoryId: '1',
        name_ko: '팟카파오 무쌉/가이',
        name_th: 'ผัดกะเพราหมูสับ/ไก่',
        description_ko: '돼지고기/닭고기 바질 볶음 덮밥',
        price: 12000,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCsL5GUVDVxZjTc3d3SJCtfnGIKI37eq8fgbT1FhOJjN90NMb7bz_qbc-6wfJA-KsNDyvCpsLVE2sCrQ4oTy_KPMvxjhxlEShdqyjwDW7ZXs1EqNM770CFCIw03sAQp7SuZ3N6f7IJfIJgPF2GvPA9fNc-6cld_So3jjlKQS-8V55c5kMghzIBDHgdoZb558JlgUf7eW0Ky-Ejhk_n5QXNaYnHaJp78x5qVXyEfAWAx0CmSyDsP9DIXuxsQPBhwyDSeQwmLE718hMld',
    },
    {
        id: '1-2',
        categoryId: '1',
        name_ko: '팟카파오 느아',
        name_th: 'ผัดกะเพราเนื้อ',
        description_ko: '소고기 바질 볶음 덮밥',
        price: 13000,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQ28C_fJuq-JIOUsrIsY1d0AP_M-7xp7Ce5SBJpQSpWUp4gyBJZycyrvpcklfuu8jK5ECRg8_uLs19Tac4CeFI5dgWEAtaVDZ4jfKZbb32EE6J9A2XmLvUiJ15OJqUooTI-_0LT-rwjlQu1jRNaFtv7kAqDAXbHGfDab59uipmtJ68VuYPhojrut-qy1zPiAXhrTmklQxOPkfwKR-8qiBxxkcFISD8br3e9BHvfOMOFpPKuqDhIzqdGmnRyHwROSxDvXSqksfRJJy2',
    },
    {
        id: '1-3',
        categoryId: '1',
        name_ko: '팟카파오 탈레',
        name_th: 'ผัดกะเพราทะเล',
        description_ko: '해산물 바질 볶음 덮밥',
        price: 15000,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCIzoW7qztP20VWRLzuQ4ovhk8i6Xkgl6TAOm6lnT6xZQow25fFyqHlWYClc2ctQgFQuzGmoA7VV7ZHhd7zvdnhKY4mQFrANJpgiUU8FtA-VubiHzeDgDSzPBq8zaCyH2DzMaUoQbQu1i6MjZPj4rZnPWM6G8DJOV5OKtlj4ghl1zc-w9e-30c4txNjyiTLnKSuoCTXdLWaZdMvDg3YARKkjOhSeDjMukY7LAihtqVCgDUB39b3xelqdf2F3N1v69d48Shr0czte5IW',
    },
    {
        id: '1-4',
        categoryId: '1',
        name_ko: '카오 팟 무',
        name_th: 'ข้าวผัดหมู',
        description_ko: '돼지고기 볶음밥',
        price: 12000,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKPoHg3F9fWats4t-uY7JofiyG1gd7qd8T8mXNaKD1cMaBkq4t_Arw4iyyy3q3gEa2tbrvNRAy3ATQAY0ho7clgRkAZmgdPbRY8mH_iEi92mCp4ElsmkyGbGi09Oo7LYnzb_d7TG6O1hk_kniDaSQ-iyUjY5_B9bciBKMFltZJokhx0L1wbwTR9iSvVNvmUgRjXK3YOIbF3YPkbILNKIH10ah7vR5tsLhJNNV_d3sQgblmEOaYHdBa40wNGaz7F-Y3Kb-BPTtMLlqh',
    },
    {
        id: '1-5',
        categoryId: '1',
        name_ko: '카오 팟 꿍',
        name_th: 'ข้าวผัดกุ้ง',
        description_ko: '새우 볶음밥',
        price: 15000,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDTPdJ7nzsfEiU_-EFrzL_k4UeOgBjaWPTiCXZvJN_Pa8THhm1os8nUXMzHKfIIxfo6PYhxIwFKy7J1A4xTbnWnJ2QpScxZ_NV5Y_mW3dHo707WR6eaVD8sEFqSP9Qc68cIOFIACsxBRxyBkWdXrwPpxElrsxaQnBk8ENSNtUYlYdioYWPMEGVkC0MsEOnYzodUKQ__-ZnsQnSgId9m0Yzpiw4vEqmDBkqRaPQ3gGd3PEpJAAt-FqkkjYQYpX-QaGZvVGEizKBokV74',
    },
    {
        id: '1-6',
        categoryId: '1',
        name_ko: '카오 팟 탈레',
        name_th: 'ข้าวผัดทะเล',
        description_ko: '해산물 볶음밥',
        price: 15000,
        image: null,
    },
    {
        id: '1-7',
        categoryId: '1',
        name_ko: '카오 무 팟 프릭깽 따이',
        name_th: 'ข้าวหมูผัดพริกแกงใต้',
        description_ko: '남부식 돼지고기 레드커리 덮밥',
        price: 12000,
        image: null,
    },
    {
        id: '1-8',
        categoryId: '1',
        name_ko: '카오 탈레 팟 프릭깽 따이',
        name_th: 'ข้าวทะเลผัดพริกแกงใต้',
        description_ko: '남부식 해산물 레드커리 덮밥',
        price: 15000,
        image: null,
    },
    {
        id: '1-9',
        categoryId: '1',
        name_ko: '카오 팟 프릭깽 무껍',
        name_th: 'ข้าวผัดพริกแกงหมูกรอบ',
        description_ko: '삼겹살 튀김 레드커리 덮밥',
        price: 15000,
        image: null,
    },
    {
        id: '1-10',
        categoryId: '1',
        name_ko: '카오 팟 프릭깽 탈레', // Typo in image? Assume standard naming
        name_th: 'ข้าวผัดพริกแกงทะเล',
        description_ko: '해산물 레드커리 볶음 덮밥',
        price: 15000,
        image: null,
    },
    {
        id: '1-11',
        categoryId: '1',
        name_ko: '카오 카나 무막',
        name_th: 'ข้าวคะน้าหมูหมัก',
        description_ko: '케일 돼지고기 볶음 덮밥',
        price: 12000,
        image: null,
    },
    {
        id: '1-12',
        categoryId: '1',
        name_ko: '카오 무텃 크라티얌',
        name_th: 'ข้าวหมูทอดกระเทียม',
        description_ko: '돼지고기 마늘 튀김 덮밥',
        price: 12000,
        image: null,
    },

    // --- Category 4: 찌개/국/커리 (Tom & Kaeng) ---
    {
        id: '4-1',
        categoryId: '4',
        name_ko: '똠얌 꿍',
        name_th: 'ต้มยำกุ้ง',
        description_ko: '새우 똠얌찌개',
        price: 15000,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBs82xpIimKb-VvthsdeyQxyqMeNwu0-bkc6IertqHT0BuiPVSiP8n5krBO6U_20b98XDypi4zj86b6igDY2l-kWKfC3EidaIZUAGl5ACsRJIB_FkoYJ-pGMHEWeQxdaXo6BT95PgksudM7f7P_Ej7-30-OEkXh1NZNLgHcxkCmatHG1jYEapgVaU4P4_qE3NbOSau0sEga-Woo1diUxCVKXAgFupI7Xa03gtxSIeAXSJwzLOXZoi8UNHLNaqChHS1v9rkqJpf4Ysg9',
    },
    {
        id: '4-2',
        categoryId: '4',
        name_ko: '파냉 무',
        name_th: 'พะแนงหมู',
        description_ko: '진한 파냉 커리 돼지고기',
        price: 13000,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3yWcWXncpIcI0UAR2nbrYgPpd11rIySSdXiUm8-VY-YQ7VB_y6JPg0utBKH4C4e1yPgEEGSqKKCbxKvopD7D2s2BljFLYHoknfgkQ0pZWVeegGjqynq6DJLEXR1NTxYNp9ee6XdwrhYh1Lxx5CadXsWaL4NPZzTG3JW8iYMIR6yEABuBACTx0H-kUU6HlMMHccfpVDPDwIQ_h1Ch9eUuAqId99AcMcd1pHMMh98xymo4lpIKZ1eehUTjZ6x1MGF9-Azv8lX2rMbjQ',
    },
];
